### ISSUE TITLE
Allow custom action creators.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [procore/redux-modules#103]
Something like
```
transformations: {
  doThing: {
    reducer: (state, action) => new state,
  }
  doThingWithCustomActionCreator: {
    actionCreator: (type, payload, meta) => action,
    reducer: (state, action) => new state,
  }
}
```

**Comment by mboperator** [comment]
Is this use case not solved by `middleware`?

**Comment by wtgtybhertgeghgtwtg** [comment]
It is, but it's a little less obvious.  But you're right, it can probably just stay in the realm of middleware.

**Comment by wtgtybhertgeghgtwtg** [comment]
For this case, I would like `middleware` to be able to accept a function as well as an array, though.
