### ISSUE TITLE
Actions within reducer not dispatched

### ISSUE THREAD

**Issue by bkniffler** [procore/redux-modules#137]
The actions are never bound to the dispatcher inside the module itself, the examples don't work with the current version. How can we dispatch?

```
const module = createModule({
  name: 'module',
  initialState: { stuff: [] },
  selector: state => state.stuff,
  transformations: {
    fetch: {
      reducer: (state, { payload }) => {
        setTimeout((x) => {
          module.actions.fetch(1234);
        }, 3000);
        return state;;
      },
    },
}
```

**Comment by mboperator** [comment]
Hey! So reducers are always supposed to return new state, this library does not handle side effects. To do what you're working, you'll want to use either `redux-sagas` or `redux-loop`
