### ISSUE TITLE
Don't Call PropTypes Warning

### ISSUE THREAD

**Issue by jcalfee** [procore/redux-modules#73]
Looks like this:

``` javascript
            payloadTypes: {
                confirm: oneOfType([string, func]),
            },
```

Triggers this warning in react 15.3.1.  There is a solution at the bottom:

https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by jcalfee** [comment]
I found a reference to this issue.  Is this still the case?

https://github.com/mboperator/redux-modules/issues/44#issuecomment-229694116
>You’ll probably want to switch to an open source fork of propTypes (I found a few, e.g. >https://github.com/aackerman/PropTypes)

**Comment by mboperator** [comment]
Good morning!

This is the implementation that calls `propTypes`:
https://github.com/mboperator/redux-modules/pull/68/files#diff-164d17b32830f9a79bd5967ecaad02d6R9

As you can see we're not really using the `propTypes` library here. To avoid this issue in my examples I ended up using the following npm module: https://www.npmjs.com/package/prop-types as a drop in replacement for React's built in propType checker.

Let me know if you have any issues!

**Comment by jcalfee** [comment]
Good to know.  In this design we decided we can just remove all of the prop types, we really are not used them.  I'm not sure if you want to use that extra parameter react provides or not so I'll leave this open.  It looks like you can silence the warning without requiring your users to use a special library.

**Comment by mboperator** [comment]
The `propCheck` middleware is going to be deprecated in this next release so I'll close the issue. Thanks for bringing this on the radar though! I'll try to fix this in the https://github.com/mboperator/redux-modules-middleware repository
