### ISSUE TITLE
Split examples to subpackages.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [procore/redux-modules#97]
[As `redux` does](https://github.com/reactjs/redux/tree/master/examples).  Having a monolithic example makes it a pain to add and view examples.  You could probably use `create-react-app` for this.

**Comment by mboperator** [comment]
This one is in [progress](https://github.com/procore/redux-modules/tree/switch-examples-to-create-react-app)

**Comment by mboperator** [comment]
Closed by https://github.com/procore/redux-modules/pull/112
